name: CI

on:
  push:
    branches: [main]

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      PACKAGE_NAME: AdrenalineGamesEditor
      SOLUTION_NAME: AdrenalineGamesEditor.sln
      PUBLISH_ARTIFACTS: false
